name: SpawnMob
main: com.jordanneil23.SpawnMob.SpawnMob
version: 1.8.2
commands:
  spawnmob:
    description:
    usage: |
  smob:
    description:
    usage: |
  sm:
    description:
    usage: |
  mspawn:
    description:
    usage: |