name: SpawnMob
author: jordanneil23
main: com.jordanneil23.SpawnMob.SpawnMob
version: 1.9.5
commands:
  spawnmob:
    description:
    usage: |
  smob:
    description:
    usage: |
  sm:
    description:
    usage: |
  mspawn:
    description:
    usage: |